"""empty message

Revision ID: b2555fc802ef
Revises: ec0bec1848f0
Create Date: 2023-11-20 15:27:21.158965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2555fc802ef'
down_revision = 'ec0bec1848f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__lookup__id'), 'lookup', ['id'])
    op.add_column('lookup_answer', sa.Column('pos', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq__lookup_answer__id'), 'lookup_answer', ['id'])
    op.create_unique_constraint(op.f('uq__phrases__id'), 'phrases', ['id'])
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('uq__phrases__id'), 'phrases', type_='unique')
    op.drop_constraint(op.f('uq__lookup_answer__id'), 'lookup_answer', type_='unique')
    op.drop_column('lookup_answer', 'pos')
    op.drop_constraint(op.f('uq__lookup__id'), 'lookup', type_='unique')
    # ### end Alembic commands ###
