"""empty message

Revision ID: ccc0e7a299f4
Revises: 00e2cd7683fd
Create Date: 2023-11-28 01:32:12.700315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc0e7a299f4'
down_revision = '00e2cd7683fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
