"""empty message

Revision ID: ffc6d3f21cb8
Revises: b2555fc802ef
Create Date: 2023-11-26 22:02:03.259544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc6d3f21cb8'
down_revision = 'b2555fc802ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lookup_answer', sa.Column('normalized_text', sa.String(), nullable=True))
    op.add_column('lookup_answer', sa.Column('normalized_text_translation', sa.String(), nullable=True))
    op.drop_column('lookup_answer', 'normilized_text_translation')
    op.drop_column('lookup_answer', 'normilized_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lookup_answer', sa.Column('normilized_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lookup_answer', sa.Column('normilized_text_translation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('lookup_answer', 'normalized_text_translation')
    op.drop_column('lookup_answer', 'normalized_text')
    # ### end Alembic commands ###
