"""empty message

Revision ID: d8f299c72bd2
Revises: ffc6d3f21cb8
Create Date: 2023-11-28 00:04:19.549959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f299c72bd2'
down_revision = 'ffc6d3f21cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrases', sa.Column('normalized_text', sa.String(), nullable=False))
    op.add_column('phrases', sa.Column('normalized_text_translation', sa.String(), nullable=False))
    op.drop_column('phrases', 'normilized_text_translation')
    op.drop_column('phrases', 'normilized_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrases', sa.Column('normilized_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('phrases', sa.Column('normilized_text_translation', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('phrases', 'normalized_text_translation')
    op.drop_column('phrases', 'normalized_text')
    # ### end Alembic commands ###
