"""empty message

Revision ID: 25668af45831
Revises: d8f299c72bd2
Create Date: 2023-11-28 00:27:40.711445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25668af45831'
down_revision = 'd8f299c72bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
