"""empty message

Revision ID: 00e2cd7683fd
Revises: 25668af45831
Create Date: 2023-11-28 00:33:41.528916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e2cd7683fd'
down_revision = '25668af45831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrases', sa.Column('explanation', sa.String(), nullable=True))
    op.add_column('phrases', sa.Column('explanation_translation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phrases', 'explanation_translation')
    op.drop_column('phrases', 'explanation')
    # ### end Alembic commands ###
