"""empty message

Revision ID: ddf896c79cde
Revises: 3b53561678bc
Create Date: 2023-11-14 22:04:02.787584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddf896c79cde'
down_revision = '3b53561678bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__token')),
    sa.UniqueConstraint('id', name=op.f('uq__token__id'))
    )
    op.create_index(op.f('ix__token__token'), 'token', ['token'], unique=True)
    op.add_column('user', sa.Column('create_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('user', sa.Column('update_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_unique_constraint(op.f('uq__user__id'), 'user', ['id'])
    op.drop_column('user', 'dt_created')
    op.drop_column('user', 'dt_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq__user__id'), 'user', type_='unique')
    op.drop_column('user', 'update_time')
    op.drop_column('user', 'create_time')
    op.drop_index(op.f('ix__token__token'), table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
